# Generated by Django 3.2.9 on 2022-12-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_documents"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
    ]
