# Generated by Django 3.2.9 on 2021-11-25 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vessels", "0001_vessel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_guests", models.PositiveIntegerField()),
                ("apa_budget", models.FloatField()),
                ("embark_location", models.CharField(max_length=255)),
                ("disembark_location", models.CharField(max_length=255)),
                ("embark_date", models.DateField()),
                ("disembark_date", models.DateField()),
                ("booking_id", models.UUIDField(default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_charters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vessel",
                        to="vessels.vessel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Charters",
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("is_principal", models.BooleanField(default=False)),
                ("emergency_contact", models.CharField(max_length=255)),
                ("emergency_phone", models.CharField(max_length=255)),
                ("address_street", models.CharField(max_length=255)),
                ("address_number", models.CharField(max_length=255)),
                ("address_city", models.CharField(max_length=255)),
                ("address_state", models.CharField(max_length=255)),
                ("address_zipcode", models.CharField(max_length=255)),
                ("address_country", models.CharField(max_length=255)),
                ("medical_issues", models.CharField(max_length=255)),
                ("allergies", models.CharField(max_length=255)),
                ("medications", models.CharField(max_length=255)),
                (
                    "food_sensitivities",
                    models.CharField(
                        choices=[
                            ("LACTOSE_INTOLERANT", "Lactose Intolerant"),
                            ("SHELLFISH_ALLERGY", "Shellfish Allergy"),
                            ("NUT_ALLERGY", "Nut Allergy"),
                            ("GLUTEN_FREE", "Gluten-Free"),
                            ("NONE", "None"),
                            ("OTHER", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("salutation_nickname", models.CharField(max_length=255)),
                ("high_priority_details", models.TextField()),
                (
                    "charter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guests",
                        to="charter.charter",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Guests",
            },
        ),
    ]
