# Generated by Django 3.2.9 on 2021-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charter",
            name="disembark_additional_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="charter",
            name="disembark_country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="charter",
            name="disembark_name_of_dock",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="charter",
            name="embark_additional_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="charter",
            name="embark_country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="charter",
            name="embark_name_of_dock",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
