# Generated by Django 3.2.9 on 2021-11-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0002_auto_20211125_1329"),
    ]

    operations = [
        migrations.AddField(
            model_name="charter",
            name="disembark_time",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="charter",
            name="embark_time",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
