# Generated by Django 3.2.9 on 2021-11-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0002_vessel_is_active"),
        ("charter", "0003_auto_20211125_1448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charter",
            name="vessel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charters",
                to="vessels.vessel",
            ),
        ),
    ]
