# Generated by Django 3.2.9 on 2021-12-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0004_alter_vessel_related_name"),
        ("charter", "0004_auto_20211130_1839"),
    ]

    operations = []
