# Generated by Django 3.2.9 on 2021-12-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "charter",
            "0006_breakfastselection_dinnerselection_lunchselection_mealandroompreferences",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DietServicesSizes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.CharField(
                        choices=[
                            ("VEGAN", "Vegan"),
                            ("VEGETARIAN", "Vegetarian"),
                            ("PALEO", "Paleo"),
                            ("PESCATARIAN", "Pescatarian"),
                            ("NONE", "None"),
                        ],
                        max_length=225,
                    ),
                ),
                ("dietary_restrictions_notes", models.TextField()),
                ("preferred_room_temperature", models.CharField(max_length=225)),
                (
                    "shirt_sizing",
                    models.CharField(
                        choices=[("MENS", "Men's"), ("WOMENS", "Women's")],
                        max_length=225,
                    ),
                ),
                (
                    "international_shirt_sizing",
                    models.CharField(
                        choices=[("US", "US"), ("UK", "UK")], max_length=225
                    ),
                ),
                (
                    "shirt_size",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                        ],
                        max_length=225,
                    ),
                ),
                (
                    "shoe_sizing",
                    models.CharField(
                        choices=[("MENS", "Men's"), ("WOMENS", "Women's")],
                        max_length=225,
                    ),
                ),
                (
                    "international_shoe_sizing",
                    models.CharField(
                        choices=[("US", "US"), ("UK", "UK")], max_length=225
                    ),
                ),
                ("shoe_size", models.PositiveIntegerField()),
                (
                    "guest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_services_sizes_preferences",
                        to="charter.guest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                (
                    "diet_services_sizes_preferences",
                    models.ManyToManyField(
                        related_name="other_services", to="charter.DietServicesSizes"
                    ),
                ),
            ],
        ),
    ]
