# Generated by Django 3.2.9 on 2021-12-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0007_dietservicessizes_otherservices"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeveragesAndAlcoholicPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("milk_note", models.TextField()),
                ("coffee_note", models.TextField()),
                ("tea_note", models.TextField()),
                ("water_note", models.TextField()),
                ("juice_note", models.TextField()),
                ("sodas_and_mixers_note", models.TextField()),
                ("add_ons_note", models.TextField()),
                (
                    "whiskey_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("whiskey_quantity", models.IntegerField(default=0)),
                (
                    "brandy_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("brandy_quantity", models.IntegerField(default=0)),
                ("vodka_name", models.CharField(blank=True, max_length=255, null=True)),
                ("vodka_quantity", models.IntegerField(default=0)),
                (
                    "tequila_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tequila_quantity", models.IntegerField(default=0)),
                ("rum_name", models.CharField(blank=True, max_length=255, null=True)),
                ("rum_quantity", models.IntegerField(default=0)),
                (
                    "liquors_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("liquors_quantity", models.IntegerField(default=0)),
                (
                    "cocktail_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cocktail_quantity", models.IntegerField(default=0)),
                (
                    "port_beer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("port_beer_quantity", models.IntegerField(default=0)),
                (
                    "red_wine_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("red_wine_quantity", models.IntegerField(default=0)),
                (
                    "white_wine_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("white_wine_quantity", models.IntegerField(default=0)),
                (
                    "champagne_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("champagne_quantity", models.IntegerField(default=0)),
                ("other_name", models.CharField(blank=True, max_length=255, null=True)),
                ("other_quantity", models.IntegerField(default=0)),
                (
                    "guest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beverages_and_alcoholic_preferences",
                        to="charter.guest",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="DietServicesSizes",
            new_name="DietServicesSizesPreferences",
        ),
        migrations.CreateModel(
            name="WaterSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                (
                    "beverages_and_alcoholic_preferences",
                    models.ManyToManyField(
                        related_name="water_selections",
                        to="charter.BeveragesAndAlcoholicPreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeaSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                (
                    "beverages_and_alcoholic_preferences",
                    models.ManyToManyField(
                        related_name="tea_selections",
                        to="charter.BeveragesAndAlcoholicPreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SodasAndMixersSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                (
                    "beverages_and_alcoholic_preferences",
                    models.ManyToManyField(
                        related_name="sodas_and_mixers_selections",
                        to="charter.BeveragesAndAlcoholicPreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MilkSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                (
                    "beverages_and_alcoholic_preferences",
                    models.ManyToManyField(
                        related_name="milk_selections",
                        to="charter.BeveragesAndAlcoholicPreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JuiceSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                (
                    "beverages_and_alcoholic_preferences",
                    models.ManyToManyField(
                        related_name="juice_selections",
                        to="charter.BeveragesAndAlcoholicPreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoffeeSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                (
                    "beverages_and_alcoholic_preferences",
                    models.ManyToManyField(
                        related_name="coffee_selections",
                        to="charter.BeveragesAndAlcoholicPreferences",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddOnsSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                (
                    "beverages_and_alcoholic_preferences",
                    models.ManyToManyField(
                        related_name="add_ons_selections",
                        to="charter.BeveragesAndAlcoholicPreferences",
                    ),
                ),
            ],
        ),
    ]
