# Generated by Django 3.2.9 on 2021-12-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0005_merge_20211201_2002"),
        ("charter", "0008_auto_20211201_2005"),
    ]

    operations = []
