# Generated by Django 3.2.9 on 2021-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0009_merge_20211201_2123"),
    ]

    operations = [
        migrations.AddField(
            model_name="charter",
            name="embark_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
