# Generated by Django 3.2.9 on 2021-12-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0010_charter_embark_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodpreferences",
            name="cheese_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="dessert_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="fish_and_shellfish_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="salad_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="soup_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foodpreferences",
            name="bread_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foodpreferences",
            name="general_cuisine_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foodpreferences",
            name="meat_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
