# Generated by Django 3.2.9 on 2021-12-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0011_auto_20211216_1513"),
    ]

    operations = [
        migrations.AddField(
            model_name="charter",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
