# Generated by Django 3.2.9 on 2021-12-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0001_create_guest_profile"),
        ("charter", "0014_auto_20211228_1759"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestdetail",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="guests.guestprofile",
            ),
        ),
    ]
