# Generated by Django 3.2.9 on 2022-01-03 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0015_guestdetail_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dietservicessizespreferences",
            options={"verbose_name_plural": "Diet, Services & Sizes Preferences"},
        ),
        migrations.AlterModelOptions(
            name="foodpreferences",
            options={"verbose_name_plural": "Food Preferences"},
        ),
        migrations.AlterModelOptions(
            name="mealandroompreferences",
            options={"verbose_name_plural": "Meal and Room Preferences"},
        ),
        migrations.AddField(
            model_name="dietservicessizespreferences",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dietservicessizespreferences",
            name="dietary_restrictions_other_notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dietservicessizespreferences",
            name="favorite_flowers",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dietservicessizespreferences",
            name="other_services_other_notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dietservicessizespreferences",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="mealandroompreferences",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mealandroompreferences",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dietservicessizespreferences",
            name="international_shoe_sizing",
            field=models.CharField(
                choices=[("US", "US"), ("UK", "UK"), ("EU", "EU")], max_length=225
            ),
        ),
    ]
