# Generated by Django 3.2.9 on 2022-01-05 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0016_auto_20220103_1921"),
    ]

    operations = [
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
