# Generated by Django 3.2.9 on 2022-01-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0017_auto_20220105_0744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietservicessizespreferences",
            name="international_shirt_sizing",
            field=models.CharField(
                choices=[("US", "US"), ("UK", "UK"), ("EU", "EU")], max_length=225
            ),
        ),
        migrations.AlterField(
            model_name="dietservicessizespreferences",
            name="shirt_size",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("L", "L"),
                    ("S", "S"),
                    ("XL", "XL"),
                    ("M", "M"),
                ],
                max_length=225,
            ),
        ),
        migrations.AlterField(
            model_name="mealandroompreferences",
            name="canapes_selection",
            field=models.CharField(
                choices=[
                    ("LIGHT", "Light"),
                    ("FULL_SELECTION", "Full Selection"),
                    ("NONE", "None"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mealandroompreferences",
            name="midafternoon_snacks",
            field=models.CharField(
                choices=[("SWEET", "Sweet"), ("SAVORY", "Savory"), ("NONE", "None")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mealandroompreferences",
            name="midmorning_snacks",
            field=models.CharField(
                choices=[("SWEET", "Sweet"), ("SAVORY", "Savory"), ("NONE", "None")],
                max_length=255,
            ),
        ),
    ]
