# Generated by Django 3.2.9 on 2022-01-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0018_auto_20220105_1948"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestdetail",
            name="food_sensitivities",
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="lactose_intolerant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="none_food_sensitivity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="nut_allergy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="other",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="other_notes",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="pronouns",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="shellfish_allergy",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="guestdetail",
            name="high_priority_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guestdetail",
            name="salutation_nickname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
