# Generated by Django 3.2.9 on 2022-01-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0019_food_sensitivities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietservicessizespreferences",
            name="shirt_size",
            field=models.CharField(
                choices=[
                    ("XS", "Extra Small"),
                    ("L", "Large"),
                    ("S", "Small"),
                    ("XL", "Extra Large"),
                    ("M", "Medium"),
                ],
                max_length=225,
            ),
        ),
    ]
