# Generated by Django 3.2.9 on 2022-01-13 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0021_charter_disembark_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="charter",
            name="principal_guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="principal_charters",
                to="charter.guestdetail",
                verbose_name="Principal Guest",
            ),
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="charters",
            field=models.ManyToManyField(
                related_name="charter_guests",
                to="charter.Charter",
                verbose_name="Trips",
            ),
        ),
    ]
