# Generated by Django 3.2.9 on 2022-01-13 20:51

from django.db import migrations


def transfer_charter_principals(apps, schema_editor):
    Charter = apps.get_model("charter", "Charter")

    for charter in Charter.objects.all():
        charter_guests = charter.guests.filter(is_principal=False)
        charter.guests.add(*charter_guests)
        charter.principal_guest = charter.guests.get(is_principal=True)
        charter.save()


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0022_many_to_many_charters"),
    ]

    operations = [
        migrations.RunPython(transfer_charter_principals),
    ]
