# Generated by Django 3.2.9 on 2022-01-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0024_remove_charter_foreign_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="breakfastselection",
            name="meal_and_room_preference",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breakfast_selection",
                to="charter.mealandroompreferences",
                verbose_name="Meal And Room Preference",
            ),
        ),
        migrations.AddField(
            model_name="dinnerselection",
            name="meal_and_room_preference",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dinner_selection",
                to="charter.mealandroompreferences",
                verbose_name="Meal And Room Preference",
            ),
        ),
        migrations.AddField(
            model_name="lunchselection",
            name="meal_and_room_preference",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lunch_selection",
                to="charter.mealandroompreferences",
                verbose_name="Meal And Room Preference",
            ),
        ),
    ]
