# Generated by Django 3.2.9 on 2022-01-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0026_migrate_selections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="breakfastselection",
            name="meal_and_room_preferences",
        ),
        migrations.RemoveField(
            model_name="dinnerselection",
            name="meal_and_room_preferences",
        ),
        migrations.RemoveField(
            model_name="lunchselection",
            name="meal_and_room_preferences",
        ),
    ]
