# Generated by Django 3.2.9 on 2022-01-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0027_remove_many_to_many_selections"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonsselection",
            name="temp_field",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="add_ons_selection",
                to="charter.beveragesandalcoholicpreferences",
                verbose_name="Beverages And Alcoholic Preferences",
            ),
        ),
        migrations.AddField(
            model_name="coffeeselection",
            name="temp_field",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coffee_selection",
                to="charter.beveragesandalcoholicpreferences",
                verbose_name="Beverages And Alcoholic Preferences",
            ),
        ),
        migrations.AddField(
            model_name="juiceselection",
            name="temp_field",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="juice_selection",
                to="charter.beveragesandalcoholicpreferences",
                verbose_name="Beverages And Alcoholic Preferences",
            ),
        ),
        migrations.AddField(
            model_name="milkselection",
            name="temp_field",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milk_selection",
                to="charter.beveragesandalcoholicpreferences",
                verbose_name="Beverages And Alcoholic Preferences",
            ),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="temp_field",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_service",
                to="charter.dietservicessizespreferences",
                verbose_name="Diet Services Sizes Preferences",
            ),
        ),
        migrations.AddField(
            model_name="sodasandmixersselection",
            name="temp_field",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sodas_and_mixers_selection",
                to="charter.beveragesandalcoholicpreferences",
                verbose_name="Beverages And Alcoholic Preferences",
            ),
        ),
        migrations.AddField(
            model_name="teaselection",
            name="temp_field",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tea_selection",
                to="charter.beveragesandalcoholicpreferences",
                verbose_name="Beverages And Alcoholic Preferences",
            ),
        ),
        migrations.AddField(
            model_name="waterselection",
            name="temp_field",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="water_selection",
                to="charter.beveragesandalcoholicpreferences",
                verbose_name="Beverages And Alcoholic Preferences",
            ),
        ),
    ]
