# Generated by Django 3.2.9 on 2022-01-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0029_migrate_beverage_selections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addonsselection",
            name="beverages_and_alcoholic_preferences",
        ),
        migrations.RemoveField(
            model_name="coffeeselection",
            name="beverages_and_alcoholic_preferences",
        ),
        migrations.RemoveField(
            model_name="juiceselection",
            name="beverages_and_alcoholic_preferences",
        ),
        migrations.RemoveField(
            model_name="milkselection",
            name="beverages_and_alcoholic_preferences",
        ),
        migrations.RemoveField(
            model_name="otherservices",
            name="diet_services_sizes_preferences",
        ),
        migrations.RemoveField(
            model_name="sodasandmixersselection",
            name="beverages_and_alcoholic_preferences",
        ),
        migrations.RemoveField(
            model_name="teaselection",
            name="beverages_and_alcoholic_preferences",
        ),
        migrations.RemoveField(
            model_name="waterselection",
            name="beverages_and_alcoholic_preferences",
        ),
    ]
