# Generated by Django 3.2.9 on 2022-01-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0030_remove_unused_models"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addonsselection",
            old_name="temp_field",
            new_name="beverages_and_alcoholic_preferences",
        ),
        migrations.RenameField(
            model_name="coffeeselection",
            old_name="temp_field",
            new_name="beverages_and_alcoholic_preferences",
        ),
        migrations.RenameField(
            model_name="juiceselection",
            old_name="temp_field",
            new_name="beverages_and_alcoholic_preferences",
        ),
        migrations.RenameField(
            model_name="milkselection",
            old_name="temp_field",
            new_name="beverages_and_alcoholic_preferences",
        ),
        migrations.RenameField(
            model_name="sodasandmixersselection",
            old_name="temp_field",
            new_name="beverages_and_alcoholic_preferences",
        ),
        migrations.RenameField(
            model_name="teaselection",
            old_name="temp_field",
            new_name="beverages_and_alcoholic_preferences",
        ),
        migrations.RenameField(
            model_name="waterselection",
            old_name="temp_field",
            new_name="beverages_and_alcoholic_preferences",
        ),
        migrations.RenameField(
            model_name="otherservices",
            old_name="temp_field",
            new_name="diet_services_sizes_preferences",
        ),
    ]
