# Generated by Django 3.2.9 on 2022-01-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0032_alter_guestdetail_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="charter",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
