# Generated by Django 3.2.9 on 2022-02-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0034_auto_20220203_2014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charter",
            name="disembark_additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="charter",
            name="embark_additional_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
