# Generated by Django 3.2.9 on 2022-02-07 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0035_auto_20220203_2125"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charter",
            name="number_of_guests",
        ),
    ]
