# Generated by Django 3.2.9 on 2022-04-19 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0037_remove_dietservicessizespreferences_favorite_flowers"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestdetail",
            name="date_of_birth",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="nationality",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="passport_expiration",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="guestdetail",
            name="passport_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
