# Generated by Django 3.2.9 on 2022-10-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0039_short_long_jet_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestdetail",
            name="emergency_relation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
