# Generated by Django 3.2.9 on 2022-11-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0040_guestdetail_emergency_relation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestdetail",
            name="pronouns",
        ),
    ]
