# Generated by Django 3.2.9 on 2022-12-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0041_remove_guestdetail_pronouns"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestdetail",
            name="passport",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Passport"
            ),
        ),
    ]
