# Generated by Django 3.2.9 on 2023-01-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0042_guestdetail_passport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestdetail",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guestdetail",
            name="passport_expiration",
            field=models.DateField(blank=True, null=True),
        ),
    ]
