# Generated by Django 3.2.9 on 2023-01-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0043_auto_20230106_0924"),
    ]

    operations = [
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="rose_wine_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="rose_wine_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="kids_allergies",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Kids Allergies"
            ),
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="kids_meals",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Kids Meals"
            ),
        ),
        migrations.AddField(
            model_name="foodpreferences",
            name="kids_meals_notes",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Kids Meals Notes"
            ),
        ),
    ]
