# Generated by Django 3.2.9 on 2023-01-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0044_auto_20230111_1321"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietservicessizespreferences",
            name="dietary_restrictions",
        ),
        migrations.RemoveField(
            model_name="dietservicessizespreferences",
            name="dietary_restrictions_notes",
        ),
        migrations.RemoveField(
            model_name="dietservicessizespreferences",
            name="dietary_restrictions_other_notes",
        ),
        migrations.RemoveField(
            model_name="dietservicessizespreferences",
            name="preferred_room_temperature",
        ),
        migrations.AddField(
            model_name="mealandroompreferences",
            name="dietary_restrictions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VEGAN", "Vegan"),
                    ("VEGETARIAN", "Vegetarian"),
                    ("PALEO", "Paleo"),
                    ("PESCATARIAN", "Pescatarian"),
                    ("NONE", "None"),
                ],
                max_length=225,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mealandroompreferences",
            name="dietary_restrictions_notes",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="mealandroompreferences",
            name="dietary_restrictions_other_notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mealandroompreferences",
            name="preferred_room_temperature",
            field=models.CharField(max_length=225, null=True),
        ),
    ]
