# Generated by Django 3.2.9 on 2023-01-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0045_auto_20230124_1809"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealandroompreferences",
            name="preferred_room_temperature",
        ),
        migrations.AddField(
            model_name="dietservicessizespreferences",
            name="preferred_room_temperature",
            field=models.CharField(max_length=225, null=True),
        ),
    ]
