# Generated by Django 3.2.9 on 2023-01-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0046_auto_20230124_1818"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealandroompreferences",
            name="favorite_flowers",
        ),
        migrations.AddField(
            model_name="dietservicessizespreferences",
            name="favorite_flowers",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
