# Generated by Django 3.2.9 on 2023-02-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0047_flowers"),
    ]

    operations = [
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_brandy",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_champagne",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_cocktail",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_liquors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_port_beer",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_red_wine",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_rose_wine",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_rum",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_tequila",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_vodka",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_whiskey",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beveragesandalcoholicpreferences",
            name="extra_white_wine",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
