# Generated by Django 3.2.9 on 2021-11-20 03:48

import admins.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0003_remove_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("authentication.user",),
            managers=[
                ("objects", admins.managers.AdminManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=25)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CAPTAIN", "Captain"),
                            ("FIRST_OFFICER", "First Officer"),
                            ("CHIEF_STEWARD", "Chief Steward/ess"),
                            ("PURSER", "Purser"),
                            ("ENGINEERING", "Engineering"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
