# Generated by Django 3.2.9 on 2021-11-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0001_create_adminprofile_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="receive_email_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
