# Generated by Django 3.2.9 on 2022-02-10 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charter", "0036_remove_charter_number_of_guests"),
        ("admins", "0002_add_receive_email_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("1_WEEK_NOTICE", "1 Week Notice"),
                            ("2_WEEK_NOTICE", "2 Week Notice"),
                            ("COMPLETED_PREFERENCE", "Completed Preference"),
                        ],
                        max_length=250,
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "guest_list",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Guest List"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="admins.adminprofile",
                        verbose_name="Admin",
                    ),
                ),
                (
                    "charter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="charter.charter",
                        verbose_name="Charter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Notification",
                "verbose_name_plural": "Admin Notifications",
            },
        ),
    ]
