# Generated by Django 3.2.9 on 2022-09-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0005_create_imo_field"),
        ("admins", "0004_seen_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="vessel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crew_members",
                to="vessels.vessel",
                verbose_name="Vessel",
            ),
        ),
    ]
