# Generated by Django 3.2.9 on 2022-12-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0005_crew_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminprofile",
            name="vessel",
        ),
    ]
