# Generated by Django 3.2.9 on 2023-02-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0006_remove_adminprofile_vessel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("CAPTAIN", "Captain"),
                    ("FIRST_OFFICER", "First Officer"),
                    ("CHIEF_STEWARD", "Chief Steward/ess"),
                    ("PURSER", "Purser"),
                    ("OTHER", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
