# Generated by Django 3.2.9 on 2023-03-15 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0010_alter_crewprofile_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=256, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=256, verbose_name="Last Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Interest"
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="About"),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_guest_information",
                        to="admins.adminprofile",
                        verbose_name="Admin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest Information",
                "verbose_name_plural": "Guest Information",
            },
        ),
    ]
