# Generated by Django 3.2.9 on 2023-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0011_guestinformation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestinformation",
            name="about",
        ),
        migrations.RemoveField(
            model_name="guestinformation",
            name="interest",
        ),
        migrations.AddField(
            model_name="guestinformation",
            name="contact_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="guestinformation",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guestinformation",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("TRANSGENDER", "Female"),
                    ("NON_BINARY", "Non-binary/Non-Conforming"),
                    ("NO_RESPONSE", "Prefer not to respond"),
                ],
                max_length=52,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="guestinformation",
            name="nationality",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guestinformation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
