# Generated by Django 3.2.9 on 2022-08-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0001_short_long_jet_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="longjetpreferencesheet",
            name="kids_allergies",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Kids Allergies"
            ),
        ),
        migrations.AddField(
            model_name="longjetpreferencesheet",
            name="kids_meals",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Kids Meals"
            ),
        ),
        migrations.AddField(
            model_name="longjetpreferencesheet",
            name="kids_meals_notes",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Kids Meals Notes"
            ),
        ),
        migrations.AddField(
            model_name="shortjetpreferencesheet",
            name="kids_allergies",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Kids Allergies"
            ),
        ),
        migrations.AddField(
            model_name="shortjetpreferencesheet",
            name="kids_meals",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Kids Meals"
            ),
        ),
        migrations.AddField(
            model_name="shortjetpreferencesheet",
            name="kids_meals_notes",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Kids Meals Notes"
            ),
        ),
        migrations.AlterField(
            model_name="longjetpreferencesheet",
            name="dietary_restrictions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VEGAN", "Vegan"),
                    ("PALEO", "Paleo"),
                    ("VEGETARIAN", "Vegetarian"),
                    ("PESCETARIAN", "Pescetarian"),
                    ("GLUTEN_FREE", "Gluten Free"),
                    ("NONE", "None"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="Dietary Restrictions",
            ),
        ),
        migrations.AlterField(
            model_name="shortjetpreferencesheet",
            name="dietary_restrictions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VEGAN", "Vegan"),
                    ("PALEO", "Paleo"),
                    ("VEGETARIAN", "Vegetarian"),
                    ("PESCETARIAN", "Pescetarian"),
                    ("GLUTEN_FREE", "Gluten Free"),
                    ("NONE", "None"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="Dietary Restrictions",
            ),
        ),
    ]
