# Generated by Django 3.2.9 on 2022-08-05 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0002_kids_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="longjetpreferencesheet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="longjetpreferencesheet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="shortjetpreferencesheet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shortjetpreferencesheet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
