# Generated by Django 3.2.9 on 2022-11-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0003_auto_20220805_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="longjetpreferencesheet",
            name="favorite_flowers",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shortjetpreferencesheet",
            name="favorite_flowers",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
