# Generated by Django 3.2.9 on 2021-11-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_add_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
