# Generated by Django 3.2.9 on 2021-12-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_create_passwordresetcode_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Profile Picture"
            ),
        ),
    ]
