# Generated by Django 3.2.9 on 2021-11-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0001_vessel"),
    ]

    operations = [
        migrations.AddField(
            model_name="vessel",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Active"),
        ),
    ]
