# Generated by Django 3.2.9 on 2022-01-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0003_alter_vessel_charter_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vessel",
            name="charter_type",
            field=models.CharField(
                choices=[
                    ("M/Y", "Motor Yacht"),
                    ("C", "Catamaran"),
                    ("S/Y", "Sail Yacht"),
                    ("F", "Fishing"),
                    ("R", "Rib"),
                ],
                max_length=50,
                verbose_name="Charter Type",
            ),
        ),
    ]
