# Generated by Django 3.2.9 on 2022-01-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0004_alter_vessel_charter_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vessel",
            name="crew_size",
        ),
        migrations.AddField(
            model_name="vessel",
            name="imo_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="International Maritime Organization #",
            ),
        ),
    ]
