# Generated by Django 3.2.9 on 2022-12-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0006_remove_adminprofile_vessel"),
        ("vessels", "0005_create_imo_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="vessel",
            name="crew_members",
            field=models.ManyToManyField(
                to="admins.AdminProfile", verbose_name="Crew Members"
            ),
        ),
    ]
