# Generated by Django 3.2.9 on 2023-01-06 08:53

from django.db import migrations, models


def change_rib_to_tender(apps, schema_editor):
    Vessel = apps.get_model("vessels", "Vessel")

    Vessel.objects.filter(charter_type="R").update(charter_type="T")


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0006_vessel_crew_members"),
    ]

    operations = [
        migrations.RunPython(change_rib_to_tender),
        migrations.AlterField(
            model_name="vessel",
            name="charter_type",
            field=models.CharField(
                choices=[
                    ("M/Y", "Motor Yacht"),
                    ("C", "Catamaran"),
                    ("S/Y", "Sail Yacht"),
                    ("F", "Fishing"),
                    ("T", "Tinder"),
                ],
                max_length=50,
                verbose_name="Charter Type",
            ),
        ),
    ]
